SELECT * FROM users;
SELECT id, name, email FROM customers;
SELECT DISTINCT department FROM employees;
SELECT * FROM orders WHERE total > 100;
SELECT name, salary FROM employees WHERE salary >= 50000 AND department = 'Engineering';
SELECT name FROM employees WHERE department = 'HR' OR department = 'Finance';
SELECT * FROM products WHERE price BETWEEN 10 AND 100;
SELECT * FROM users WHERE name LIKE 'A%';
SELECT * FROM orders WHERE status IN ('pending', 'shipped', 'delivered');
SELECT * FROM employees WHERE manager_id IS NULL;
SELECT * FROM orders WHERE created_at IS NOT NULL;
SELECT COUNT(*) FROM users;
SELECT department, COUNT(*) FROM employees GROUP BY department;
SELECT department, AVG(salary) FROM employees GROUP BY department HAVING AVG(salary) > 60000;
SELECT * FROM employees ORDER BY salary DESC;
SELECT * FROM orders ORDER BY created_at ASC LIMIT 10;
SELECT * FROM orders LIMIT 5 OFFSET 10;
SELECT e.name, d.name FROM employees e JOIN departments d ON e.dept_id = d.id;
SELECT e.name, d.name FROM employees e LEFT JOIN departments d ON e.dept_id = d.id;
SELECT name AS full_name, salary AS monthly_pay FROM employees;
INSERT INTO users VALUES (1, 'Alice', 'alice@mail.com');
INSERT INTO users (id, name, email) VALUES (2, 'Bob', 'bob@mail.com');
UPDATE users SET name = 'Charlie' WHERE id = 3;
UPDATE employees SET salary = salary + 5000 WHERE department = 'Engineering';
DELETE FROM users WHERE id = 10;
DELETE FROM orders WHERE created_at < '2023-01-01';
CREATE TABLE students (id INT PRIMARY KEY, name VARCHAR(100) NOT NULL, age INT);
CREATE TABLE orders (id INT PRIMARY KEY AUTO_INCREMENT, customer_id INT, total FLOAT, created_at DATE);
CREATE TABLE products (id INT, name VARCHAR(255) NOT NULL, price DECIMAL(10,2), UNIQUE(name));
DROP TABLE temp_table;
SELECT * FROM users WHERE id IN (SELECT user_id FROM orders WHERE total > 500);
SELECT name, (salary * 12) AS annual_salary FROM employees;
SELECT MAX(salary) FROM employees;
SELECT MIN(price), MAX(price), AVG(price) FROM products;
